package com.gmrodrigues.js.sandbox;

import org.junit.Test;

import java.io.File;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
import static org.junit.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'glauber' at '28/03/16 13:37' with Gradle 2.9
 *
 * @author glauber, @date 28/03/16 13:37
 */
public class JsSandboxFastEvaluatorTest
{
    @Test public void testSource() {
        JsSandboxEvaluator evaluator = new JsSandboxFastEvaluator();
        evaluator.setSource("'Hello ' + 'World'");
        String result = (String) evaluator.exec();
        String expected = "Hello World";
        assertThat("exec must return correct value", result, is(expected));
    }

    @Test public void testPutVar() {
        JsSandboxEvaluator evaluator = new JsSandboxFastEvaluator();
        evaluator.putVar("name", "Glauber");
        evaluator.setSource("'Hello ' + name");
        String result = (String) evaluator.exec();
        String expected = "Hello Glauber";
        assertThat("exec must return correct value", result, is(expected));
    }

    @Test public void testLoadJs() {
        JsSandboxEvaluator evaluator = new JsSandboxFastEvaluator();
        evaluator.loadJs("testdata/js/script.js");
        evaluator.setSource("message");
        String result = (String) evaluator.exec();
        String expected = "Howdy Stranger!";
        assertThat("someLibraryMethod should return 'true'", result, is(expected));
    }
}
